### ISSUE TITLE
Make the terminal split more configurable.

### ISSUE THREAD

**Issue by henricattoire** [urbainvaes/vim-ripple#8]
Right now, you can only specify if you want to have a vertical split or not. It is not possible to, for example, give the split a width or special name. I was wondering if you could maybe implement this? I would suggest using `term_start()` to achieve this (`g:ripple_winpos` becomes redundant of course, you could replace it with `g:ripple_config`). I am willing to implement this if you don't have the time (although it should be a rather small change).

**Comment by urbainvaes** [comment]
Hi, and thank you very much for the suggestion. In neovim, it is possible to specify the width or height by setting for example
```
let g:ripple_winpos = "topleft 10"
```
but I hadn't realized that this does not work in vim. A workaround might be to use `topleft 10 new +term\ ++curwin` in the plugin code, instead of `topleft 10 term`, but perhaps a more general solution of the type you suggest would be better. Something like
```
topleft10 new | call term_start("ipython", {"term_name": "hello", "curwin": 1})
```
might be enough for most purposes, and it could be configurable with two options: `g:ripple_winpos` for the position, and then a vim-only (because neovim doesn't have `term_start`) `g:ripple_config` with a dictionary to pass to `term_start`? Do you think this would be general enough?

An less general alternative would be to expose only one additional option for the buffer name, which could be employed in both `vim` and `nvim`.

**Comment by urbainvaes** [comment]
I pushed some changes that I tested with
```
let g:ripple_winpos = "topleft 20"
let g:ripple_term_name = "hello"
```
and the plugin seems to work as expected. Do you think this is configurable enough, or do you have use cases that require additional configurability?

**Comment by henricattoire** [comment]
Work fine, thanks! It's just that I also really like the `term_kill` feature of term start which allows you to tell vim to automatically close on exit code (for example when typing `exit()` in python3 repl). I just feel one dictionary setting (`ripple_config`) is better than having a dozen separate settings. Of course then you would have to implement it in a more complex way to work with neovim so maybe that's a tradeoff you're not willing to make?

**Comment by urbainvaes** [comment]
Yes, this sounds reasonable. I added an option `g:ripple_term_options` to pass options to `term_start()`. So in `vim`, you can now configure the REPL with only two options, namely `g:ripple_winpos` and `g:ripple_term_options`. In principle, the position of the window could be configured also with `term_start()`, but I feel like the difference between the `vim` and `nvim` interfaces would then be a bit confusing.

What do you think?

**Comment by henricattoire** [comment]
I would also keep the `g:ripple_winpos` otherwise nvim users might be confused on how they can setup this plugin. I'm now definitely moving to this plugin from vim-slime, good job!

**Comment by urbainvaes** [comment]
Thanks for your input!
